import Head from "next/head";
import Link from "next/link";
// import { useRouter } from "next/router";

export const getStaticPaths = async () => {
    const response = await fetch('https://jsonplaceholder.typicode.com/users/')

    const data = await response.json();

    const paths = data.map((user) => {
        return{
            params: {id:user.id.toString()}
        }
    })
    return {
        paths,
        fallback: false,
    }
}

// for id fetching

export const getStaticProps = async (context) => {
   const id =  context.params.id

   const response = await fetch('https://jsonplaceholder.typicode.com/users/' + id)

   const data = await response.json();

   return{
    props: {user: data}
   }
}


function Detail({ user }) {
    // const router = useRouter()

    // if(router.isFallback){
    //     return<h1>Loading...</h1>
    // }
    return(
        <>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div>
            <Link href='/' style={{textDecoration:'none'}}>Home</Link> 
            <h1>{user.name}</h1>
            <h2>{user.username}</h2>
            <h2>{user.email}</h2>
            <h2>{user.phone}</h2>
            <h2>{user.website}</h2>
        </div>
        </>
    )
}
export default Detail