import Head from "next/head"

function AboutUsPage() {
    return(
        <>
         <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div>
            <h1>AboutUsPage</h1>
        </div>
        </>
    )
}
export default AboutUsPage